# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mongify}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andrew Kalek"]
  s.date = %q{2010-08-19}
  s.default_executable = %q{mongify}
  s.description = %q{Mongify allows you to map your data from a sql database and into a mongodb document database.}
  s.email = %q{andrew.kalek@anlek.com}
  s.executables = ["mongify"]
  s.extra_rdoc_files = [
    "CHANGELOG.rdoc",
     "README.rdoc"
  ]
  s.files = [
    "CHANGELOG.rdoc",
     "Gemfile",
     "Gemfile.lock",
     "Manifest",
     "README.rdoc",
     "Rakefile",
     "bin/mongify",
     "lib/core_ext/array.rb",
     "lib/core_ext/hash.rb",
     "lib/mongify.rb",
     "lib/mongify/cli/application.rb",
     "lib/mongify/cli/help_command.rb",
     "lib/mongify/cli/options.rb",
     "lib/mongify/cli/report.rb",
     "lib/mongify/cli/version_command.rb",
     "lib/mongify/configuration.rb",
     "lib/mongify/database/base_config.rb",
     "lib/mongify/database/column.rb",
     "lib/mongify/database/no_sql_config.rb",
     "lib/mongify/database/sql_config.rb",
     "lib/mongify/database/table.rb",
     "lib/mongify/exceptions.rb",
     "lib/mongify/translation.rb",
     "lib/mongify/translation/generator.rb",
     "lib/mongify/ui.rb",
     "mongify.gemspec"
  ]
  s.homepage = %q{http://github.com/anlek/mongify}
  s.rdoc_options = ["--charset=UTF-8", "--title", "Mongify -- SQL db to Mongo db", "--main", "README", "--line-numbers", "--inline-source"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Move your data from a sql database to a mongodb document database.}
  s.test_files = [
    "spec/default.watch",
     "spec/files",
     "spec/mongify",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/tmp",
     "features/generator.feature",
     "features/options.feature",
     "features/step_definitions",
     "features/support"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 2.3"])
      s.add_runtime_dependency(%q<net-ssh>, [">= 2.0"])
      s.add_development_dependency(%q<jeweler>, [">= 1.4"])
      s.add_development_dependency(%q<rspec>, ["= 1.3"])
      s.add_development_dependency(%q<mocha>, [">= 0.9.8"])
      s.add_development_dependency(%q<yard>, [">= 0.5.3"])
      s.add_development_dependency(%q<watchr>, [">= 0.6"])
      s.add_development_dependency(%q<sqlite3-ruby>, [">= 1.3"])
      s.add_development_dependency(%q<mysql>, [">= 2.8.1"])
    else
      s.add_dependency(%q<activerecord>, [">= 2.3"])
      s.add_dependency(%q<net-ssh>, [">= 2.0"])
      s.add_dependency(%q<jeweler>, [">= 1.4"])
      s.add_dependency(%q<rspec>, ["= 1.3"])
      s.add_dependency(%q<mocha>, [">= 0.9.8"])
      s.add_dependency(%q<yard>, [">= 0.5.3"])
      s.add_dependency(%q<watchr>, [">= 0.6"])
      s.add_dependency(%q<sqlite3-ruby>, [">= 1.3"])
      s.add_dependency(%q<mysql>, [">= 2.8.1"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 2.3"])
    s.add_dependency(%q<net-ssh>, [">= 2.0"])
    s.add_dependency(%q<jeweler>, [">= 1.4"])
    s.add_dependency(%q<rspec>, ["= 1.3"])
    s.add_dependency(%q<mocha>, [">= 0.9.8"])
    s.add_dependency(%q<yard>, [">= 0.5.3"])
    s.add_dependency(%q<watchr>, [">= 0.6"])
    s.add_dependency(%q<sqlite3-ruby>, [">= 1.3"])
    s.add_dependency(%q<mysql>, [">= 2.8.1"])
  end
end

